src/ExpenseTracker.Web/Controllers/BudgetController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using ExpenseTracker.Core.Dto.Transaction;
using ExpenseTracker.Core.Exceptions;
using ExpenseTracker.Core.Logging;
using ExpenseTracker.Core.Repositories.Interface;
using ExpenseTracker.Core.Services.Interface;
using ExpenseTracker.Infrastructure.Extensions;
using ExpenseTracker.Web.Providers.Interface;
using ExpenseTracker.Web.ViewModels;
using ExpenseTracker.Web.ViewModels.Budget;
using ExpenseTracker.Web.ViewModels.Transaction;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ExpenseTracker.Web.Controllers
{
    [Authorize]
    public class BudgetController : Controller
    {
        private readonly IApplicationLogger<BudgetController> _logger;
        private readonly IUserProvider _userProvider;
        private readonly INotyfService _notifyService;
        private readonly IBudgetRepository _budgetRepository;
        private readonly IBudgetService _budgetService;

        public BudgetController(
            IApplicationLogger<BudgetController> logger,
            IUserProvider userProvider,
            INotyfService notifyService,
            IBudgetRepository budgetRepository,
            IBudgetService budgetService)
        {
            _logger = logger;
            _userProvider = userProvider;
            _notifyService = notifyService;
            _budgetRepository = budgetRepository;
            _budgetService = budgetService;
        }

        public async Task<IActionResult> Index(BudgetIndexViewModel vm)
        {
            var defaultWorkspaceToken = (await _userProvider.GetDefaultWorkspaceToken());
            var budgets = _budgetRepository
                .GetPredicatedQueryable(a => a.Workspace.Token == defaultWorkspaceToken)
                .OrderByDescending(x => x.Id)
                .ToList();
            vm.Budgets = budgets;
            return View(vm);
        }

        public IActionResult SetBudget()
        {
            var (firstDay, lastDay) = DateTime.Now.GetDateBound();
            var vm = new BudgetViewModel
            {
                FromDate = firstDay,
                ToDate = lastDay
            };
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> SetBudget(BudgetViewModel vm)
        {
            try
            {
                await _budgetService.Create(new BudgetCreateDto()
                {
                    RecBy = await _userProvider.GetCurrentUser(),
                    Workspace = await _userProvider.GetDefaultWorkspace(),
                    Amount = vm.Amount,
                    FromDate = vm.FromDate,
                    ToDate = vm.ToDate,
                    Description = vm.Description
                });

                _notifyService.Success($"Budget set Successfully for [{vm.FromDate:d} to {vm.ToDate:d}]");
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message, e);
                _notifyService.Error(e.Message);
            }

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(long id)
        {
            try
            {
                var budget = await _budgetRepository.FindAsync(id)
                             ?? throw new Exception("Budget not found.");

                await _budgetService.Delete(budget.Id);

                _notifyService.Success("Budget Deleted Successfully");
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message, e);
                _notifyService.Error(e.Message);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

src/ExpenseTracker.Web/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ExpenseTracker.Web.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {
        // GET
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/ExpenseTracker.Web/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ExpenseTracker.Core.Entities;
using ExpenseTracker.Core.Entities.Common;
using ExpenseTracker.Core.Repositories.Interface;
using ExpenseTracker.Infrastructure.Extensions;
using ExpenseTracker.Web.Providers.Interface;
using ExpenseTracker.Web.ViewModels.Report;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ExpenseTracker.Web.Controllers
{
    [Authorize]
    public class ReportController : Controller
    {
        private readonly ITransactionRepository _transactionRepository;
        private readonly IUserProvider _userProvider;

        public ReportController(ITransactionRepository transactionRepository,IUserProvider userProvider)
        {
            _transactionRepository = transactionRepository;
            _userProvider = userProvider;
        }
        // GET
        public async Task<IActionResult> Index(DailyReportViewModel reportViewModel)
        {
            var workspaceToken = (await _userProvider.GetCurrentUser()).DefaultWorkspace.Token;
            var transactionQueryable =
                _transactionRepository.GetPredicatedQueryable(a => a.Workspace.Token == workspaceToken);

            if (reportViewModel.TransactionDate != null)
            {
                transactionQueryable  = transactionQueryable.Where(a => a.TransactionDate.Date == reportViewModel.TransactionDate.Value.Date);
            }
            else
            {
                transactionQueryable  = transactionQueryable.Where(a => a.TransactionDate.Date == DateTime.Today.Date);
                reportViewModel.TransactionDate = DateTime.Now;
            }

            reportViewModel.DailyTransactions = transactionQueryable.Include(a=>a.TransactionCategory).OrderByDescending(a => a.EntryDate).ToList();
        
            return View(reportViewModel);
        }

        public async Task<IActionResult> Monthly(MonthlyReportViewModel reportViewModel)
        {
            var workspaceToken = (await _userProvider.GetCurrentUser()).DefaultWorkspace.Token;
            var transactionQueryable =
                _transactionRepository.GetPredicatedQueryable(a => a.Workspace.Token == workspaceToken);
                
            if (reportViewModel is { FromDate: { }, ToDate: { } })
            {
                transactionQueryable  = transactionQueryable.Where(a => a.TransactionDate.Date >= reportViewModel.FromDate.Value.Date && a.TransactionDate.Date <= reportViewModel.ToDate.Value.Date);
            }
            else
            {
                var (firstDay, lastDay) = DateTime.Now.GetDateBound();
                transactionQueryable  = transactionQueryable.Where(a => a.TransactionDate.Date >= DateTime.Today.AddMonths(-1).Date && a.TransactionDate.Date <= DateTime.Today.Date);
                reportViewModel.FromDate = firstDay;
                reportViewModel.ToDate = lastDay;
            }
            
            reportViewModel.MonthlyTransactions = transactionQueryable.Include(a=>a.TransactionCategory).OrderByDescending(a => a.EntryDate).ToList();
            
            return View(reportViewModel);
        }
        
        public async Task<IActionResult> StatementReport(StatementReportViewModel reportViewModel)
        {
            var workspaceToken = (await _userProvider.GetCurrentUser()).DefaultWorkspace.Token;
            var transactionQueryable =
                _transactionRepository.GetPredicatedQueryable(a => a.Workspace.Token == workspaceToken);
                
            if (reportViewModel is { FromDate: { }, ToDate: { } })
            {
                transactionQueryable  = transactionQueryable.Where(a => a.TransactionDate.Date >= reportViewModel.FromDate.Value.Date && a.TransactionDate.Date <= reportViewModel.ToDate.Value.Date);
            }
            else
            {
                var (firstDay, lastDay) = DateTime.Now.GetDateBound();
                transactionQueryable  = transactionQueryable.Where(a => a.TransactionDate.Date >= DateTime.Today.AddMonths(-1).Date && a.TransactionDate.Date <= DateTime.Today.Date);
                reportViewModel.FromDate = firstDay;
                reportViewModel.ToDate = lastDay;
            }

            var report = transactionQueryable.Include(a => a.TransactionCategory).OrderByDescending(a => a.EntryDate);
            reportViewModel.StatementReport = new ValueTuple<IList<Transaction>, IList<Transaction>>(
                report.Where(a => a.Type == TransactionType.Expense).ToList(),
                report.Where(a => a.Type == TransactionType.Income).ToList());
            
            return View(reportViewModel);
        }
    }
}

src/ExpenseTracker.Web/Controllers/SettingController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ExpenseTracker.Web.Controllers
{
    [Authorize]
    public class SettingController : Controller
    {
        // GET
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/ExpenseTracker.Web/Views/Shared/_Footer.cshtml
<footer class="footer footer-transparent d-print-none">
    <div class="container">
        <div class="row text-center align-items-center flex-row-reverse">
            <div class="col-lg-auto ms-lg-auto">
                <ul class="list-inline list-inline-dots mb-0">
                    <li class="list-inline-item">
                        <a href="/" class="link-secondary" rel="noopener">v1.0.0</a>
                    </li>
                </ul>
            </div>
            <div class="col-12 col-lg-auto mt-3 mt-lg-0">
                <ul class="list-inline list-inline-dots mb-0">
                    <li class="list-inline-item">
                        Copyright &copy; @DateTime.Now.Year
                        <a href="." class="link-secondary">Expense Tracker</a>.
                        All rights reserved.
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

src/ExpenseTracker.Web/Views/Shared/_Header.cshtml
@using ExpenseTracker.Web.Providers.Interface
@inject IUserProvider _userProvider
@{
    var currentUser = await _userProvider.GetCurrentUser();
}

<header class="navbar navbar-expand-md navbar-light d-print-none">
    <div class="container-xl">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-menu">
            <span class="navbar-toggler-icon"></span>
        </button>
        <h1 class="navbar-brand navbar-brand-autodark d-none-navbar-horizontal pe-0 pe-md-3">
            <a href=".">
                <img src="~/static/expense-tracker-logo.svg" width="175" height="32" alt="Expense Tracker" class="navbar-brand-image">
            </a>
        </h1>
        <div class="navbar-nav flex-row order-md-last">
            <div class="nav-item dropdown d-none d-md-flex me-3">
                <a href="#" class="nav-link px-0" data-bs-toggle="dropdown" tabindex="-1"
                   aria-label="Show notifications">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24"
                         stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round"
                         stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                        <path d="M10 5a2 2 0 0 1 4 0a7 7 0 0 1 4 6v3a4 4 0 0 0 2 3h-16a4 4 0 0 0 2 -3v-3a7 7 0 0 1 4 -6"/>
                        <path d="M9 17v1a3 3 0 0 0 6 0v-1"/>
                    </svg>
                    <span class="badge bg-red"></span>
                </a>
                <div class="dropdown-menu dropdown-menu-end dropdown-menu-card">
                    <div class="card">
                        <div class="card-body">
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus ad amet consectetur
                            exercitationem fugiat in ipsa ipsum, natus odio quidem quod repudiandae sapiente. Amet
                            debitis et magni maxime necessitatibus ullam.
                        </div>
                    </div>
                </div>
            </div>
            <div class="nav-item dropdown">
                <a href="#" class="nav-link d-flex lh-1 text-reset p-0" data-bs-toggle="dropdown"
                   aria-label="Open user menu">
                    <span class="avatar avatar-sm" style='background-image:url("/static/avatars/profile.jpg")'></span>
                    <div class="d-none d-xl-block ps-2">
                        <div>@currentUser.FirstName @currentUser.LastName</div>
                        <div class="mt-1 small text-muted">User</div>
                    </div>
                </a>
                <div class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
                    <a asp-action="Index" asp-controller="Profile" class="dropdown-item">Profile & account</a>
                    <a asp-action="Index" asp-controller="Setting" class="dropdown-item">Settings</a>
                      <div class="dropdown-divider"></div>
                    <a asp-action="Logout" asp-controller="Account" class="dropdown-item">Logout</a>
                </div>
            </div>
        </div>
    </div>
</header>

src/ExpenseTracker.Web/Views/Shared/_LayoutSecondary.cshtml
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
    <link rel="icon" href="~/static/expense-tracker-icon.svg">
    <title>@ViewData["Title"] | Expense Tracker</title>
    <!-- CSS files -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" href="~/dist/css/tabler.min.css"  asp-append-version="true"/>
    
    <link rel="stylesheet" href="~/css/app.css" asp-append-version="true"/>
    
    @await RenderSectionAsync("Styles", false)
  </head>
  <body class="antialiased">
   @RenderBody()
  <!-- Libs JS -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  
  <script src="~/dist/js/tabler.min.js" asp-append-version="true"></script>
  <!--    Section Scripts-->
   @await Component.InvokeAsync("Notyf")

  @await RenderSectionAsync("Scripts", false)
  
  @await RenderSectionAsync("_ValidationScriptsPartial",false)

  </body>
</html>

src/ExpenseTracker.Web/Views/Shared/_Navigation.cshtml
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

<div class="navbar-expand-md">
    <div class="collapse navbar-collapse" id="navbar-menu">
        <div class="navbar navbar-light">
            <div class="container-xl">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Index" is-active-route>
                            <span class="nav-link-icon d-md-none d-lg-inline-block">
                                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                    <path stroke="none" d="M0 0h24v24H0z" fill="none"/><polyline points="5 12 3 12 12 3 21 12 19 12"/><path d="M5 12v7a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-7"/><path d="M9 21v-6a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v6"/>
                                </svg>
                            </span>
                            <span class="nav-link-title">
                                Home
                            </span>
                        </a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#navbar-base" data-bs-toggle="dropdown" role="button" aria-expanded="false">
                            <span class="nav-link-icon d-md-none d-lg-inline-block">
                                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                    <path stroke="none" d="M0 0h24v24H0z" fill="none"/><polyline points="12 3 20 7.5 20 16.5 12 21 4 16.5 4 7.5 12 3"/><line x1="12" y1="12" x2="20" y2="7.5"/><line x1="12" y1="12" x2="12" y2="21"/><line x1="12" y1="12" x2="4" y2="7.5"/><line x1="16" y1="5.25" x2="8" y2="9.75"/>
                                </svg>
                            </span>
                            <span class="nav-link-title">
                                Transaction
                            </span>
                        </a>
                        <div class="dropdown-menu">
                            <div class="dropdown-menu-columns">
                                <div class="dropdown-menu-column">

                                    <a class="dropdown-item" asp-action="Index" asp-controller="TransactionCategory" is-active-route>
                                        <span class="nav-link-icon d-md-none d-lg-inline-block">
                                            <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                                <path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M16.7 8a3 3 0 0 0 -2.7 -2h-4a3 3 0 0 0 0 6h4a3 3 0 0 1 0 6h-4a3 3 0 0 1 -2.7 -2"/><path d="M12 3v3m0 12v3"/>
                                            </svg>
                                        </span> Transaction Category
                                    </a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="Transaction" is-active-route>
                                        <span class="nav-link-icon d-md-none d-lg-inline-block">
                                            <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                                <path stroke="none" d="M0 0h24v24H0z" fill="none"/><polyline points="12 3 20 7.5 20 16.5 12 21 4 16.5 4 7.5 12 3"/><line x1="12" y1="12" x2="20" y2="7.5"/><line x1="12" y1="12" x2="12" y2="21"/><line x1="12" y1="12" x2="4" y2="7.5"/><line x1="16" y1="5.25" x2="8" y2="9.75"/>
                                            </svg>
                                        </span> Transaction
                                    </a>

                                    <div class="dropdown-divider"></div>

                                    <a class="dropdown-item" asp-action="Index" asp-controller="Budget" is-active-route>
                                        <span class="nav-link-icon d-md-none d-lg-inline-block">
                                            <span class="nav-link-icon d-md-none d-lg-inline-block">
                                                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                                    <path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M9 5h-2a2 2 0 0 0 -2 2v12a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-12a2 2 0 0 0 -2 -2h-2"/><rect x="9" y="3" width="6" height="4" rx="2"/><path d="M14 11h-2.5a1.5 1.5 0 0 0 0 3h1a1.5 1.5 0 0 1 0 3h-2.5"/><path d="M12 17v1m0 -8v1"/>
                                                </svg>
                                            </span>
                                        </span>
                                        Set Budget
                                    </a>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#navbar-base" data-bs-toggle="dropdown" role="button" aria-expanded="false">
                            <span class="nav-link-icon d-md-none d-lg-inline-block">
                                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                    <path stroke="none" d="M0 0h24v24H0z" fill="none"/><line x1="4" y1="19" x2="20" y2="19"/><polyline points="4 15 8 9 12 11 16 6 20 10 20 15 4 15"/>
                                </svg>
                            </span>
                            <span class="nav-link-title">
                                Report
                            </span>
                        </a>
                        <div class="dropdown-menu">
                            <div class="dropdown-menu-columns">
                                <div class="dropdown-menu-column">

                                    <a class="dropdown-item" asp-action="Index" asp-controller="Report" is-active-route>
                                        <span class="nav-link-icon d-md-none d-lg-inline-block">
                                            <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                                <path stroke="none" d="M0 0h24v24H0z" fill="none"/><line x1="4" y1="19" x2="20" y2="19"/><polyline points="4 15 8 9 12 11 16 6 20 10"/>
                                            </svg>
                                        </span> Daily
                                    </a>
                                    <a class="dropdown-item" asp-action="Monthly" asp-controller="Report" is-active-route>
                                        <span class="nav-link-icon d-md-none d-lg-inline-block">
                                            <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                                <path stroke="none" d="M0 0h24v24H0z" fill="none"/><rect x="3" y="12" width="6" height="8" rx="1"/><rect x="9" y="8" width="6" height="12" rx="1"/><rect x="15" y="4" width="6" height="16" rx="1"/><line x1="4" y1="20" x2="18" y2="20"/>
                                            </svg>
                                        </span> Monthly
                                    </a>
                                    
                                    <div class="dropdown-divider"></div>
                                    
                                    <a class="dropdown-item" asp-action="StatementReport" asp-controller="Report" is-active-route>
                                        <span class="nav-link-icon d-md-none d-lg-inline-block">
                                            <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                                <path stroke="none" d="M0 0h24v24H0z" fill="none"/><rect x="3" y="12" width="6" height="8" rx="1"/><rect x="9" y="8" width="6" height="12" rx="1"/><rect x="15" y="4" width="6" height="16" rx="1"/><line x1="4" y1="20" x2="18" y2="20"/>
                                            </svg>
                                        </span> Statement Report
                                    </a>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="Activity" is-active-route>
                            <span class="nav-link-icon d-md-none d-lg-inline-block">
                                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                    <path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M3 12h4l3 8l4 -16l3 8h4"/>
                                </svg>
                            </span>
                            <span class="nav-link-title">
                                Activity
                            </span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="Setting" is-active-route>
                            <span class="nav-link-icon d-md-none d-lg-inline-block">
                                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                    <path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M10.325 4.317c.426 -1.756 2.924 -1.756 3.35 0a1.724 1.724 0 0 0 2.573 1.066c1.543 -.94 3.31 .826 2.37 2.37a1.724 1.724 0 0 0 1.065 2.572c1.756 .426 1.756 2.924 0 3.35a1.724 1.724 0 0 0 -1.066 2.573c.94 1.543 -.826 3.31 -2.37 2.37a1.724 1.724 0 0 0 -2.572 1.065c-.426 1.756 -2.924 1.756 -3.35 0a1.724 1.724 0 0 0 -2.573 -1.066c-1.543 .94 -3.31 -.826 -2.37 -2.37a1.724 1.724 0 0 0 -1.065 -2.572c-1.756 -.426 -1.756 -2.924 0 -3.35a1.724 1.724 0 0 0 1.066 -2.573c-.94 -1.543 .826 -3.31 2.37 -2.37c1 .608 2.296 .07 2.572 -1.065z"/><circle cx="12" cy="12" r="3"/>
                                </svg>
                            </span>
                            <span class="nav-link-title">
                                Setting
                            </span>
                        </a>
                    </li>
                </ul>
                <div class="my-2 my-md-0 flex-grow-1 flex-md-grow-0 order-first order-md-last">
                    @if (HttpContextAccessor.HttpContext.Request.Path != "/Workspace/Create")
                    {
                        @await Html.PartialAsync("_WorkspaceComponent")
                    }
                </div>
            </div>
        </div>
    </div>
</div>