src/ExpenseTracker.Web/ViewModels/TransactionCategory/TransactionCategoryIndexViewModel.cs
using System.Collections.Generic;
using System.Linq;

namespace ExpenseTracker.Web.ViewModels.TransactionCategory
{
    public class TransactionCategoryIndexViewModel
    {
        public IOrderedEnumerable<Core.Entities.TransactionCategory> TransactionCategories { get; set; }
    }
}

src/ExpenseTracker.Web/ViewModels/TransactionCategory/TransactionCategoryViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using ExpenseTracker.Core.Constants;
using ExpenseTracker.Core.Entities.Common;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ExpenseTracker.Web.ViewModels.TransactionCategory
{
    public class TransactionCategoryViewModel
    {
        public int TransactionCategoryId { get; set; }
        [Required]
        [MinLength(3)]
        [Display(Name = "Category Name")]
        public string Name { get; set; }

        [Display(Name = "Color")]
        public string Color { get; set; }

        public readonly List<Colors.Color> ColorList = Colors.GetColors;


        [Display(Name = "Icon")]
        public string Icon { get; set; }
        
        public IEnumerable<SelectListItem> IconSelectList => CategoryIcon.Icons.Select(a => new SelectListItem()
        {
            Text = $"{a.Value} {a.Key}",
            Value = a.Value,
            Selected = Icon == a.Value
        }).ToList();
        
        [Display(Name = "Type")]
        public string Type { get; set; }

        public static SelectList TypeSelectList => new SelectList(TransactionType.ValidTypes);

    }
}

src/ExpenseTracker.Web/Controllers/TransactionCategoryController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using ExpenseTracker.Core.Dto.TransactionCategory;
using ExpenseTracker.Core.Exceptions;
using ExpenseTracker.Core.Logging;
using ExpenseTracker.Core.Repositories.Interface;
using ExpenseTracker.Core.Services.Interface;
using ExpenseTracker.Web.ViewModels.TransactionCategory;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ExpenseTracker.Web.Controllers
{
    [Authorize]
    public class TransactionCategoryController : Controller
    {
        private readonly ITransactionCategoryRepository _transactionCategoryRepository;
        private readonly ITransactionCategoryService _transactionCategoryService;
        private readonly IApplicationLogger<TransactionCategoryController> _logger;
        private readonly INotyfService _notifyService;

        public TransactionCategoryController(ITransactionCategoryRepository transactionCategoryRepository,
            ITransactionCategoryService transactionCategoryService,
            IApplicationLogger<TransactionCategoryController> logger,INotyfService notifyService)
        {
            _transactionCategoryRepository = transactionCategoryRepository;
            _transactionCategoryService = transactionCategoryService;
            _logger = logger;
            _notifyService = notifyService;
        }
        
        public async Task<IActionResult> Index(TransactionCategoryIndexViewModel transactionCategoryIndexViewModel)
        {
            var transactionCategories = await _transactionCategoryRepository.GetAllAsync();
            transactionCategoryIndexViewModel.TransactionCategories = transactionCategories.OrderBy(a=>a.Id);
            return View(transactionCategoryIndexViewModel);
        }
        
        [HttpGet]
        public IActionResult Create()
        {
            var transactionCategoryViewModel = new TransactionCategoryViewModel();
            return View(transactionCategoryViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(TransactionCategoryViewModel transactionCategoryViewModel)
        {
            try
            {
                if (!ModelState.IsValid) return View(transactionCategoryViewModel);

                await _transactionCategoryService.Create(new TransactionCategoryCreateDto()
                {
                    
                    Color = transactionCategoryViewModel.Color,
                    Type = transactionCategoryViewModel.Type,
                    Name = transactionCategoryViewModel.Name,
                    Icon = transactionCategoryViewModel.Icon
                });
            
                
                _notifyService.Success("Transaction Category Create Successfully");
                
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message,e);
                _notifyService.Error(e.Message);
            }
            return RedirectToAction(nameof(Index));

        }

        public async Task<IActionResult> Edit(int transactionCategoryId)
        {
            try
            {
                var transactionCategory = await _transactionCategoryRepository.FindAsync(transactionCategoryId)
                     ?? throw new TransactionCategoryNotFoundException();

                var transactionViewModel = new TransactionCategoryViewModel()
                {
                    TransactionCategoryId = transactionCategory.Id,
                    Name = transactionCategory.CategoryName,
                    Icon = transactionCategory.Icon,
                    Type = transactionCategory.Type,
                    Color = transactionCategory.Color
                };
            
                return View(transactionViewModel);
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message,e);
                _notifyService.Error(e.Message);
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(TransactionCategoryViewModel transactionCategoryViewModel)
        {
            try
            {
                if (!ModelState.IsValid) return View(transactionCategoryViewModel);

                await _transactionCategoryService.Update(new TransactionCategoryUpdateDto()
                {
                    TransactionCategoryId = transactionCategoryViewModel.TransactionCategoryId,
                    Color = transactionCategoryViewModel.Color,
                    Type = transactionCategoryViewModel.Type,
                    Name = transactionCategoryViewModel.Name,
                    Icon = transactionCategoryViewModel.Icon
                });
            
                _notifyService.Success("Transaction Category Updated Successfully");
                
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message,e);
                _notifyService.Error(e.Message);
            }
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int transactionCategoryId)
        {
            try
            {
                var transactionCategory = await _transactionCategoryRepository.FindAsync(transactionCategoryId)
                     ?? throw new TransactionCategoryNotFoundException();

                await _transactionCategoryService.Delete(transactionCategory.Id);
                
                _notifyService.Success("Transaction Category Deleted Successfully");
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message,e);
                _notifyService.Error(e.Message);
            }
            return RedirectToAction(nameof(Index));
        }
        
        
        
    }
}

src/ExpenseTracker.Web/Views/TransactionCategory/Create.cshtml
@using ExpenseTracker.Web.ViewModels.TransactionCategory
@using ExpenseTracker.Core.Entities.Common
@using ExpenseTracker.Core.Constants
@model ExpenseTracker.Web.ViewModels.TransactionCategory.TransactionCategoryViewModel

@{
    ViewData["Title"] = "Transaction Category";
    Layout = "_Layout";
}

@section PageTitle
{
    <div class="page-header d-print-none">
        <div class="row align-items-center">
            <div class="col">
                <!-- Page pre-title -->
                <div class="page-pretitle">
                    Create
                </div>
                <h2 class="page-title">
                    @ViewData["Title"]
                </h2>
            </div>
            <!-- Page title actions -->
            <div class="col-auto ms-auto d-print-none">
                <div class="btn-list">
                    <a asp-action="Index" asp-controller="TransactionCategory" class="btn btn-default d-none d-sm-inline-block">
                        <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none"/><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/>
                        </svg>
                        Cancel
                    </a>
                    <a asp-action="Index" asp-controller="TransactionCategory" class="btn btn-default d-sm-none d-sm-inline-block btn-icon" aria-label="Create new Transaction Category">
                        <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none"/><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/>
                        </svg>
                    </a>
                </div>
            </div>
        </div>
    </div>
}


<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">@ViewData["Title"]</h3>
        </div>
        <div class="card-body">
            <form method="post" asp-action="Create" asp-controller="TransactionCategory">
                <div class="form-group mb-3 row">
                    @Html.LabelFor(a => a.Name, new { @class = "form-label col-3 col-form-label" })
                    <div class="col">
                        <input type="text" asp-for="Name" class="form-control" placeholder="Enter Category Name" autofocus>
                    </div>
                </div>
                <div class="form-group mb-3 row">
                    @Html.LabelFor(a => a.Type, new { @class = "form-label col-3 col-form-label" })
                    <div class="col">
                        <select asp-for="Type" asp-items="TransactionCategoryViewModel.TypeSelectList" class="form-control" id="select-type"></select>
                    </div>
                </div>
                <div class="form-group mb-3 row">
                    @Html.LabelFor(a => a.Icon, new { @class = "form-label col-3 col-form-label" })
                    <div class="col">
                        <select asp-for="Icon" class="form-select form-control" placeholder="Select a date" id="select-icon" value="">
                            @foreach (var (Key, Value) in CategoryIcon.Icons)
                            {
                                <option value="@Key" data-custom-properties="@Value">@Key</option>
                            }
                        </select>
                    </div>
                </div>

                <div class="form-group mb-3 row">
                    @Html.LabelFor(a => a.Color, new { @class = "form-label col-3 col-form-label" })
                    <div class="col">
                        <div class="row g-2">
                            @foreach (var color in Model.ColorList)
                            {
                                <div class="col-auto">
                                    <label class="form-colorinput" title="@color.name">
                                        <input asp-for="Color" type="radio" value="@color.hexValue" class="form-colorinput-input" data-com.bitwarden.browser.user-edited="yes">
                                        <span class="form-colorinput-color bg-@color.name.ToLowerInvariant()"></span>
                                    </label>
                                </div>
                            }
                        </div>
                    </div>
                </div>
                <div class="form-footer">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>


@section Scripts
{
    <script>
        // @@formatter:off
        document.addEventListener("DOMContentLoaded", function () {
        	var el;
        	window.Choices && (new Choices(el = document.getElementById('select-icon'), {
        		classNames: {
        			containerInner: el.className,
        			input: 'form-control',
        			inputCloned: 'form-control-sm',
        			listDropdown: 'dropdown-menu',
        			itemChoice: 'dropdown-item',
        			activeState: 'show',
        			selectedState: 'active',
        		},
        		shouldSort: false,
        		searchEnabled: false,
        		callbackOnCreateTemplates: function(template) {
        			const classNames = this.config.className,
        			itemSelectText = this.config.itemSelectText;
        			return {
        				item: function(classNames, data) {
        					return template('<div class="' + String(classNames.item) + ' ' + String( data.highlighted ? classNames.highlightedState : classNames.itemSelectable ) + '" data-item data-id="' + String(data.id) + '" data-value="' + String(data.value) + '"' + String(data.active ? 'aria-selected="true"' : '') + '' + String(data.disabled ? 'aria-disabled="true"' : '') + '><span class="dropdown-item-indicator"> <img class="avatar avatar-xs" src="data:image/svg+xml;utf8,' + data.customProperties + '"></span>' + String(data.label) + '</div>');
        				},
        				choice: function(classNames, data) {
        					console.log('data', data);
        					return template('<div class="' + String(classNames.item) + ' ' + String(classNames.itemChoice) + ' ' + String( data.disabled ? classNames.itemDisabled : classNames.itemSelectable ) + '" data-select-text="' + String(itemSelectText) + '" data-choice  ' + String( data.disabled ? 'data-choice-disabled aria-disabled="true"' : 'data-choice-selectable' ) + ' data-id="' + String(data.id) + '" data-value="' + String(data.value) + '" ' + String( data.groupId > 0 ? 'role="treeitem"' : 'role="option"' ) + ' ><span class="dropdown-item-indicator"><img class="avatar avatar-xs" src="data:image/svg+xml;utf8,' + data.customProperties + '"></span>' + String(data.label) + '</div>');
        				},
        			};
        		},
        	}));
        });
            document.addEventListener("DOMContentLoaded", function () {
            	var el;
            	window.Choices && (new Choices(el = document.getElementById('select-type'), {
            		classNames: {
            			containerInner: el.className,
            			input: 'form-control',
            			inputCloned: 'form-control-sm',
            			listDropdown: 'dropdown-menu',
            			itemChoice: 'dropdown-item',
            			activeState: 'show',
            			selectedState: 'active',
            		},
            		shouldSort: false,
            		searchEnabled: false,
            	}));
            });
            // @@formatter:on
      </script>
}

src/ExpenseTracker.Web/Views/TransactionCategory/Edit.cshtml
@using ExpenseTracker.Web.ViewModels.TransactionCategory
@using ExpenseTracker.Core.Entities.Common
@using ExpenseTracker.Core.Constants
@model ExpenseTracker.Web.ViewModels.TransactionCategory.TransactionCategoryViewModel

@{
    ViewData["Title"] = "Transaction Category";
    Layout = "_Layout";
}

@section PageTitle
{
    <div class="page-header d-print-none">
        <div class="row align-items-center">
            <div class="col">
                <!-- Page pre-title -->
                <div class="page-pretitle">
                    Edit
                </div>
                <h2 class="page-title">
                    @ViewData["Title"]
                </h2>
            </div>
            <!-- Page title actions -->
            <div class="col-auto ms-auto d-print-none">
                <div class="btn-list">
                    <a asp-action="Index" asp-controller="TransactionCategory" class="btn btn-default d-none d-sm-inline-block">
                        <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none"/><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/>
                        </svg>
                        Cancel
                    </a>
                    <a asp-action="Index" asp-controller="TransactionCategory" class="btn btn-default d-sm-none d-sm-inline-block btn-icon" aria-label="Create new Transaction Category">
                        <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none"/><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/>
                        </svg>
                    </a>
                </div>
            </div>
        </div>
    </div>
}



<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">@ViewData["Title"]</h3>
        </div>
        <div class="card-body">
            <form method="post" asp-action="Edit" asp-controller="TransactionCategory">
                <input type="hidden" asp-for="TransactionCategoryId">
                <div class="form-group mb-3 row">
                    @Html.LabelFor(a => a.Name, new { @class = "form-label col-3 col-form-label" })
                    <div class="col">
                        <input type="text" asp-for="Name" class="form-control" placeholder="Enter Category Name" autofocus>
                    </div>
                </div>
                <div class="form-group mb-3 row">
                    @Html.LabelFor(a => a.Type, new { @class = "form-label col-3 col-form-label" })
                    <div class="col">
                        <select asp-for="Type" asp-items="TransactionCategoryViewModel.TypeSelectList" class="form-control" id="select-type"></select>
                    </div>
                </div>
                <div class="form-group mb-3 row">
                    @Html.LabelFor(a => a.Icon, new { @class = "form-label col-3 col-form-label" })
                    <div class="col">
                        <select asp-for="Icon" class="form-select form-control" placeholder="Select a date" id="select-icon" value="">
                            @foreach (var (Key, Value) in CategoryIcon.Icons)
                            {
                                <option value="@Key" data-custom-properties="@Value">@Key</option>
                            }
                        </select>
                    </div>
                </div>

                <div class="form-group mb-3 row">
                    @Html.LabelFor(a => a.Color, new { @class = "form-label col-3 col-form-label" })
                    <div class="col">
                        <div class="row g-2">
                            @foreach (var color in Model.ColorList)
                            {
                                <div class="col-auto">
                                    <label class="form-colorinput" title="@color.name">
                                        <input asp-for="Color" type="radio" value="@color.hexValue" class="form-colorinput-input" data-com.bitwarden.browser.user-edited="yes">
                                        <span class="form-colorinput-color bg-@color.name.ToLowerInvariant()"></span>
                                    </label>
                                </div>
                            }
                        </div>
                    </div>
                </div>
                <div class="form-footer">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>


@section Scripts
{
    <script>
        // @@formatter:off
        document.addEventListener("DOMContentLoaded", function () {
        	var el;
        	window.Choices && (new Choices(el = document.getElementById('select-icon'), {
        		classNames: {
        			containerInner: el.className,
        			input: 'form-control',
        			inputCloned: 'form-control-sm',
        			listDropdown: 'dropdown-menu',
        			itemChoice: 'dropdown-item',
        			activeState: 'show',
        			selectedState: 'active',
        		},
        		shouldSort: false,
        		searchEnabled: false,
        		callbackOnCreateTemplates: function(template) {
        			var classNames = this.config.className,
        			itemSelectText = this.config.itemSelectText;
        			return {
        				item: function(classNames, data) {
        					return template('<div class="' + String(classNames.item) + ' ' + String( data.highlighted ? classNames.highlightedState : classNames.itemSelectable ) + '" data-item data-id="' + String(data.id) + '" data-value="' + String(data.value) + '"' + String(data.active ? 'aria-selected="true"' : '') + '' + String(data.disabled ? 'aria-disabled="true"' : '') + '><span class="dropdown-item-indicator"> <img class="avatar avatar-xs" src="data:image/svg+xml;utf8,' + data.customProperties + '"></span>' + String(data.label) + '</div>');
        				},
        				choice: function(classNames, data) {
        					console.log('data', data);
        					return template('<div class="' + String(classNames.item) + ' ' + String(classNames.itemChoice) + ' ' + String( data.disabled ? classNames.itemDisabled : classNames.itemSelectable ) + '" data-select-text="' + String(itemSelectText) + '" data-choice  ' + String( data.disabled ? 'data-choice-disabled aria-disabled="true"' : 'data-choice-selectable' ) + ' data-id="' + String(data.id) + '" data-value="' + String(data.value) + '" ' + String( data.groupId > 0 ? 'role="treeitem"' : 'role="option"' ) + ' ><span class="dropdown-item-indicator"><img class="avatar avatar-xs" src="data:image/svg+xml;utf8,' + data.customProperties + '"></span>' + String(data.label) + '</div>');
        				},
        			};
        		},
        	}));
        });
            document.addEventListener("DOMContentLoaded", function () {
            	var el;
            	window.Choices && (new Choices(el = document.getElementById('select-type'), {
            		classNames: {
            			containerInner: el.className,
            			input: 'form-control',
            			inputCloned: 'form-control-sm',
            			listDropdown: 'dropdown-menu',
            			itemChoice: 'dropdown-item',
            			activeState: 'show',
            			selectedState: 'active',
            		},
            		shouldSort: false,
            		searchEnabled: false,
            	}));
            });
            // @@formatter:on
      </script>
}